stages:
  training:
    cmd: python scr/training.py --path=params.yaml
    deps:
    - scr/model.py
    - data/raw/water_potability.csv
    params:
    - paths
    - train
    outs:
    - models/model.pk
